/*
 * RMServerAssist
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package router

import (
	"github.com/gin-gonic/gin"
	"github.com/wintbiit/ors-ui/internal"
)

// PingGet - Ping
func PingGet(c *gin.Context) {
	respondOk(c, "pong")
}

// VersionGet - 版本信息
func VersionGet(c *gin.Context) {
	respondOk(c, internal.Version)
}
