/*
 * RMServerAssist
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package router

type ResponseRobotInfoArray struct {
	Message string `json:"message"`

	Timestamp int32 `json:"timestamp"`

	Data []RobotInfo `json:"data"`
}
