/*
 * RMServerAssist
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package router

type RobotInfo struct {
	Team string `json:"team"`

	Teamid int32 `json:"teamid"`

	Robotid int32 `json:"robotid"`

	Name string `json:"name"`

	Level int32 `json:"level"`

	Exp int32 `json:"exp"`

	ExpLevelUp int32 `json:"expLevelUp"`

	IsBalance bool `json:"isBalance"`

	Bullet int32 `json:"bullet"`

	Hp int32 `json:"hp"`

	MaxHp int32 `json:"maxHp"`
}
